name: Automated Git Commits and Sync

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]

jobs:
  auto-commit-and-sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Auto commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git add .
        git commit -m "🤖 Automated commit: $(date +'%Y-%m-%d %H:%M:%S')

        - Auto-sync project updates
        - Preserve all changes and documentation
        - Maintain continuous integration

        🤖 Generated with [Claude Code](https://claude.ai/code)

        Co-Authored-By: Claude <noreply@anthropic.com>"
        git push

    - name: Sync to All Platforms (Notion, Replit, Cursor)
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        # Sync to Notion via webhook
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "event": "github_commit",
            "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'",
            "data": {
              "repository": "${{ github.repository }}",
              "commit_sha": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}",
              "message": "Automated multi-platform sync",
              "changes": "'$(git diff --name-only HEAD~1 HEAD | wc -l)' files changed",
              "platforms": ["github", "notion", "replit", "cursor"]
            },
            "source": "GitHub-Actions-MultiSync"
          }' \
          https://flashfusion.co/api/zapier/incoming-webhook || echo "Notion webhook failed, continuing..."
        
        # Trigger Replit sync webhook (if configured)
        if [ -n "$REPLIT_WEBHOOK_URL" ]; then
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "event": "github_update",
              "repository": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}"
            }' \
            "$REPLIT_WEBHOOK_URL" || echo "Replit webhook failed, continuing..."
        fi
        
        # Trigger Cursor workspace update
        echo "Creating Cursor workspace configuration..."
        echo '{
          "folders": [
            {"name": "FlashFusion-Unified", "path": "./FlashFusion-Unified"},
            {"name": "Inner Odyssey Kids", "path": "./inner-odyssey-kids"},
            {"name": "Customer Support Agent", "path": "./customer-support-agent"},
            {"name": "Financial Data Analyst", "path": "./financial-data-analyst"}
          ],
          "settings": {
            "cursor.ai.enabled": true,
            "editor.formatOnSave": true
          }
        }' > anthropic-quickstarts.code-workspace

    - name: Deploy to Vercel (if needed)
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        # Trigger Vercel deployment via webhook (if configured)
        curl -X POST \
          -H "Content-Type: application/json" \
          https://api.vercel.com/v1/integrations/deploy/prj_flashfusion/github || echo "Vercel deployment skipped"

  checkpoint-save:
    runs-on: ubuntu-latest
    needs: auto-commit-and-sync
    if: always()

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate checkpoint
      run: |
        mkdir -p checkpoints
        echo "# FlashFusion Automated Checkpoint - $(date)" > checkpoints/checkpoint-$(date +%Y%m%d-%H%M%S).md
        echo "" >> checkpoints/checkpoint-$(date +%Y%m%d-%H%M%S).md
        echo "## Project Status" >> checkpoints/checkpoint-$(date +%Y%m%d-%H%M%S).md
        echo "- **Timestamp**: $(date -u +%Y-%m-%dT%H:%M:%S.000Z)" >> checkpoints/checkpoint-$(date +%Y%m%d-%H%M%S).md
        echo "- **Commit**: ${{ github.sha }}" >> checkpoints/checkpoint-$(date +%Y%m%d-%H%M%S).md
        echo "- **Branch**: ${{ github.ref_name }}" >> checkpoints/checkpoint-$(date +%Y%m%d-%H%M%S).md
        echo "" >> checkpoints/checkpoint-$(date +%Y%m%d-%H%M%S).md
        echo "## File Structure" >> checkpoints/checkpoint-$(date +%Y%m%d-%H%M%S).md
        find . -type f -name "*.md" -o -name "*.json" -o -name "*.js" -o -name "*.ts" -o -name "*.tsx" | head -50 >> checkpoints/checkpoint-$(date +%Y%m%d-%H%M%S).md

    - name: Commit checkpoint
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add checkpoints/
        git commit -m "📋 Checkpoint: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push || echo "Push failed, continuing..."